apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "intelligent-content-organizer.fullname" . }}-config
  labels:
    {{- include "intelligent-content-organizer.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
